name: Weapp Build & Upload

on:
  #  push:
  #    branches: [master]
  #  pull_request:
  #    branches: [master]
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 ｜ 留空会读取package.json'
      desc:
        description: '项目备注 | 留空会读取最后一次commit'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.22'

      - name: Install Dependencies
        run: npm i

      - name: Build weapp
        run: npm run build:weapp

      - name: actions.mini-program
        uses: echoings/actions.mini-program@main
        with:
          project_type: miniProgram
          action_type: upload
          project_path: ./dist
          version: ${{ github.event.inputs.version }}
          remark: ${{ github.event.inputs.desc }}
          command_options: --enable-es6
            --project-ignores=['node_modules/**/*']
        env:
          MINI_APP_ID: ${{ secrets.APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.UPLOAD_PRIVATE_KEY }}
