name: Weapp Build

on:
  #  push:
  #    branches: [master]
  #  pull_request:
  #    branches: [master]
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 ｜ 留空会读取package.json'
      desc:
        description: '项目备注 | 留空会读取最后一次commit'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.22'

      - name: Install Dependencies
        run: npm i

      - name: Build weapp
        run: npm run build:weapp

      # 从 secrets.UPLOAD_PRIVATE_KEY 生成私钥文件
      # see Project/Settings/Secrets
      - name: Generate private key for upload
        run: echo "$UPLOAD_PRIVATE_KEY" > private.key
        env:
          UPLOAD_PRIVATE_KEY: ${{ secrets.UPLOAD_PRIVATE_KEY }}
      # 上传代码
      - name: Upload to WeChat
        run: npx mp-ci upload ./dist --pkp=./private.key --ver ${{ github.event.inputs.version }} --desc ${{ github.event.inputs.desc }} -V
